### ISSUE TITLE
Icon is a copy of Ri-li

### ISSUE THREAD

**Issue by bbhtt** [flathub/io.github.petitlapin.Li-ri#1]
@petitlapin, Hello, we are tracking a bunch of applications with trademark violations or icons that are a copy of other apps and this one came up in the list.

While it is not a trademark violation, the icon is a direct copy of https://flathub.org/apps/net.sourceforge.Ri-li I highly suggest to use your own distinct icon for the fork to not confuse people. (The names are already quite similar)

I think 2 months is a reasonable time period for us to wait for the icon to be changed.

You can find some resources for icon guidelines in https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/quality-guidelines#app-icon

**Comment by petitlapin** [comment]
@bbhtt hi, thanks for raising the issue.
This application is a fork of Ri-Li, which is not maintained since more than 15 years. This fork mostly includes the different patches of Ri-Li to compile with "recent" compilers and uses SDL2 (where Ri-Li uses SDL1.2 which last release was 12 years ago).

Would it make sense to deprecate Ri-Li in favor of this fork (and potentially remove it so it would fix this issue) to at least have a up-to-date version?

I've tried to contact the original developer but he hasn't answered (he probably does not check this mail anymore as he stopped developing the game 16 years ago).

**Comment by bbhtt** [comment]
I'd rather not, it may happen that the developer will come back.

If you can, I'd highly recommend coming up with a distinct icon.

Otherwise if you can't, as this is a fork and the original app is open source I think you can get away with some slight modifications along with recolouring parts of it.

**Comment by petitlapin** [comment]
If the original author comes back, then I'll drop this application, its only reason to exist is to use up-to-date librairies.

I'll update the icon, probably by recoloring parts as I'm not good with drawing software bu I'm open if anyone has a better icon to update it.

**Comment by bbhtt** [comment]
If you can show some pictures of the new icon, that'd be nice.

**Comment by petitlapin** [comment]
![logo_BRG](https://github.com/flathub/io.github.petitlapin.Li-ri/assets/1957734/02b294f2-5357-4124-89bb-e62e60beca39)
![logo_RBY](https://github.com/flathub/io.github.petitlapin.Li-ri/assets/1957734/68074d79-11bd-4967-895a-00900dad15d9)

**Comment by petitlapin** [comment]
Basically the logo is generated from [povray](https://www.povray.org/) (I won't go in details, I don't know much how it works).

I have in my hands the following colors:
* black
* blue
* red
* green
* yellow
* "sapin" (which is the color of the base of the train, wood)

**Comment by bbhtt** [comment]
First one seems fine. I'd also update the screenshots since they show ri-li.

**Comment by bbhtt** [comment]
![image](https://github.com/flathub/io.github.petitlapin.Li-ri/assets/62639087/a9331d4a-eb00-468e-bbc9-4c36fd582418)
